### PR TITLE
fix: add note for plural table name in migration scripts

### LINKED ISSUE #168: Platformatic DB table name convention not mentioned
I found when define tables with singular name eg: User, Role. The openapi spec is generated with duplicated ID. This cause re-declaration error when generate client Typescript definitions.

image

I tried change table names to plural and it does fixed the problem.  

image

### PR DESCRIPTION
**Pull request by sytranvn**
Fix #168

Add note for table naming convention.

### CODE REVIEW

**Comment by mcollina** [comment]
Thanks for reporting! Can you send this to the https://github.com/platformatic/platformatic/tree/main/docs?

**Comment by sytranvn** [comment]
@mcollina I updated main document as well.

**Comment by mcollina** [comment]
Thanks, could you please send the change to https://github.com/platformatic/platformatic/tree/main/docs? That'as the source of truth for the docs.

**Comment by sytranvn** [comment]
Sorry I didn't notice the link is to main repo. Here's the PR
https://github.com/platformatic/platformatic/pull/3248

**Pull request closed without merging**
